### Load_Census_Data
#### This script imports 2017 Peruvian national census data and distribute to 1km x 1km grids. The original census data was obtained from the [Nathional Institute of Statistics and Information (INEI)](http://censos2017.inei.gob.pe/redatam/).


Donghoon Lee, Nov-2-2019

In [1]:
import os
import numpy as np
import pandas as pd
import gdal
import rasterio
import fhvuln as fhv

### Load 2017 INEI Census data:
- C2P1: Type of Housing (hous, 0-1)
- PAGE5: Percent children under 5 years
- PAGE65: Percent of elderly population (65+ years)
- PFEMALE: Percent females
- PDISABL: Percent population with disability
- PMEDINS: Percent population with health insurance
- PNOSWALL: Percent households without strong walls
- PNOWATER: Percent households without public water supply
- PNOELEC: Percent households without electricity
- PNOSEWAGE: Percent households without sewage infrastructure
- PLITERACY: Percent population who cannot read and write
- PNOPRIEDU: Percent population who don't complete primary education
- PNOCOLLEGE: Percent population who don't complete college degree
- PRENT: Percentage of rented houses
- ANUMBFAMILY: Averaged Numer of people in family
- PPHONE: Percent households with cell phone or landline
- PAUTOMOBILE: Percent households with automobiles

In [100]:
input_names = [['PAGE5','pos','person','Children under 5 years (%)'],
               ['PAGE65','pos','person','Elder population (65+ years) (%)'],
               ['PFEMALE','pos','person','Percent females'],
               ['PDISABL','pos','person','Percent population with disability'],
               ['PMEDINS','neg','person','Percent population with health insurance'],
               ['PNOSWALL','pos','house','Percent households without strong walls'],
               ['PNOWATER','pos','house','Percent households without public water supply'],
               ['PNOELEC','pos','house','Percent households without electricity'],
               ['PNOSEWAGE','pos','house','Percent households without sewage infrastructure'],
               ['PLITERACY','pos','person','Percent population who cannot read and write'],
               ['PNOPRIEDU','pos','person','Percent population who don''t complete primary education'],
               ['PNOCOLLEGE','pos','person','Percent population who don''t complete college degree'],
               ['PRENT','pos','house','Percentage of rented houses'],
               ['ANUMBFAMILY','pos','house','Averaged Numer of people in family'],
               ['PPHONE','neg','house','Percent households with cell phone or landline'],
               ['PAUTOMOBILE','neg','house','Percent households with automobiles']]
data_name = pd.DataFrame(input_names, columns=['Name','Sign','Type','Description'])

In [78]:
# Label values is manually exported and translated
fn_label = os.path.join('data','census','label_values.xlsx')

# C2P1: Type of Housing (hous, 0-1) 
# (#house_Kutcha_and_Jhupri / #house_total)
# *Pucca means high quality materials (e.g., cement or RCC)
# *Kutcha & Jhupri means weaker materials (e.g., mud, clay, lime, or thatched)
df1 = fhv.ineiCensus(os.path.join('data','census','C2P1.xlsx'), fn_label)
totalHous1 = df1.sum(axis=1).sum()
df2 = fhv.ineiCensus(os.path.join('data','census','C2P2.xlsx'), fn_label)
totalHous2 = df2.sum(axis=1).sum()


# POPULATION DATA
"""
Surveyed population:  29,381,884
Ommited population:    1,855,501
Total population:     31,237,385  
"""
df = fhv.ineiCensus(os.path.join('data','census','EDQUINQ.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data = pd.DataFrame(index=df.index)  # This should be located at here (#IDDIST=1873)
popu = df.sum(axis=1)           # Total population: 29381884
# - PAGE5 Percent children under 5 years
data['PAGE5'] = df[df.columns[1]]/df.sum(axis=1)
# - PAGE65: Percent of elderly population (65+ years)
data['PAGE65'] = df[df.columns[14:]].sum(axis=1)/df.sum(axis=1)
# - PFEMALE: Percent females
df = fhv.ineiCensus(os.path.join('data','census','C5P2.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PFEMALE'] = df['Woman']/df.sum(axis=1)

#########
# Percent housholds that are female owned
# *** DOWNLOAD ***
#########

# DISABILITY
# - PDISABL: Percent population with disability
df = fhv.ineiCensus(os.path.join('data','census','P09DISC.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PDISABL'] = 1 - df[df.columns[-1]]/df.sum(axis=1)

# MEDICAL INSURANCE
# - PMEDINS: Percent population with health insurance
df = fhv.ineiCensus(os.path.join('data','census','P08AFILIA.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PMEDINS']= 1 - df[df.columns[-1]]/df.sum(axis=1)

# BUILT ENVIRONMENT
# - PNOSWALL: Percent households without strong walls
df = fhv.ineiCensus(os.path.join('data','census','C2P3.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
hous = df.sum(axis=1)           # Total households 7698900
data['PNOSWALL'] = 1 - df[df.columns[1:4]].sum(axis=1)/df.sum(axis=1)
# - PNOWATER: Percent household without public water supply
df = fhv.ineiCensus(os.path.join('data','census','C2P6.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PNOWATER'] = 1 - df[df.columns[1:3]].sum(axis=1)/df.sum(axis=1)
# - PNOELEC: Percent household without electricity
df = fhv.ineiCensus(os.path.join('data','census','C2P11.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PNOELEC'] = df[df.columns[2]]/df.sum(axis=1)
# - PNOSEWAGE: Percent household without sewage infrastructure
# This excludes 'Public drainage network within the dwelling' and
# 'Public drainage network outside the home, but inside the building'
df = fhv.ineiCensus(os.path.join('data','census','C2P10.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PNOSEWAGE']= 1 - df[df.columns[1:3]].sum(axis=1)/df.sum(axis=1)

# EDUCATION
# - PLITERACY: Percent population who cannot read and write
df = fhv.ineiCensus(os.path.join('data','census','C5P12.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PLITERACY'] = df[df.columns[2]]/df.sum(axis=1)
# - PNOPRIEDU: Percent population who don't complete primary education
df = fhv.ineiCensus(os.path.join('data','census','C5P13NIV.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PNOPRIEDU'] = df[df.columns[1:3]].sum(axis=1)/df.sum(axis=1)
# - PNOCOLLEGE: Percent population who don't complete college degree
data['PNOCOLLEGE'] = df[df.columns[1:-2]].sum(axis=1)/df.sum(axis=1)

# HOUSING
# - PRENT: Percentage of rented houses
# Includes: 'Rented', 'Assignment', 'Another way'
df = fhv.ineiCensus(os.path.join('data','census','C2P13.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PRENT'] = df[df.columns[[1,4,5]]].sum(axis=1)/df.sum(axis=1)

# FAMILY STRUCTURE
# - ANUMBFAMILY: Averaged Numer of people in family
df = fhv.ineiCensus(os.path.join('data','census','C4P1.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['ANUMBFAMILY'] = df[df.columns[1:]].values.dot(np.arange(31))/df.sum(axis=1)

# SOCIOECONOMIC CHARACTERISTICS
########
#UPDATE: Find cross table from REDATUM
########
# - PPHONE: Percent households with cell phone or landline
df = fhv.ineiCensus(os.path.join('data','census','C3P210.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PPHONE'] = df[df.columns[1]]/df.sum(axis=1)
# - PAUTOMOBILE: Percent households with automobiles
df = fhv.ineiCensus(os.path.join('data','census','C3P214.xlsx'), fn_label)
df = fhv.distCorrect(df, 'sum')
data['PAUTOMOBILE'] = df[df.columns[1]]/df.sum(axis=1)

In [135]:
df

,District,"If you have a car, truck","Does not have a car, truck"
IDDIST,,,
10101,"Amazonas, Chachapoyas, distrito de Chachapoyas",890,7469
10102,"Amazonas, Chachapoyas, distrito de Asunción",0,104
10103,"Amazonas, Chachapoyas, distrito de Balsas",13,342
10104,"Amazonas, Chachapoyas, distrito de Cheto",5,215
10105,"Amazonas, Chachapoyas, distrito de Chiliquin",0,206
...,...,...,...
250303,"Ucayali, Padre Abad, distrito de Curimana",57,1827
250304,"Ucayali, Padre Abad, distrito de Neshuya",85,1840
250305,"Ucayali, Padre Abad, distrito de Alexander Von...",55,1240
250401,"Ucayali, Purús, distrito de Purús",4,684
120699,"Junín, Satipo, distrito de MazamariJunín, Sati...",630,21254

### Load 510 Dashboards data

In [53]:
risk = pd.read_csv('./data/510_community_risk.csv', sep=';')
risk_name = np.array(list(risk.columns))
impact = pd.read_csv('./data/510_impact_database.csv', sep=';')
impact_name = np.array(list(impact.columns))

### Missing data control
INEI data and 510 data has missing data at some districts. Here, we fill those values by taking the average value of their neighbors. This is done using the spatial weights matrix `w`.

In [134]:
data.loc[[120604, 126006, ]]

,PAGE5,PAGE65,PFEMALE,PDISABL,PMEDINS,PNOSWALL,PNOWATER,PNOELEC,PNOSEWAGE,PLITERACY,PNOPRIEDU,PNOCOLLEGE,PRENT,ANUMBFAMILY,PPHONE,PAUTOMOBILE
IDDIST,,,,,,,,,,,,,,,,
120604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
import pysal as ps
w = ps.lib.weights.Queen.from_shapefile('./data/DISTRITOS.shp', idVariable='IDDIST')
w.transform = 'R'

('WARNING: ', '211302', ' is an island (no neighbors)')
('WARNING: ', '210103', ' is an island (no neighbors)')

/Users/dlee/anaconda3/envs/dlee_sovi/lib/python3.6/site-packages/pysal/lib/weights/weights.py:168: UserWarning: There are 2 disconnected observations
  Island ids: 210103, 211302
  " Island ids: %s" % ', '.join(str(island) for island in self.islands))

In [124]:
data.loc[np.isnan(data['PAGE5'])]

,PAGE5,PAGE65,PFEMALE,PDISABL,PMEDINS,PNOSWALL,PNOWATER,PNOELEC,PNOSEWAGE,PLITERACY,PNOPRIEDU,PNOCOLLEGE,PRENT,ANUMBFAMILY,PPHONE,PAUTOMOBILE
IDDIST,,,,,,,,,,,,,,,,
120604,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ps.lib.weights.spatial_lag.lag_spatial(w, shp_fips.MHSEVAL_ALT)

In [117]:
dbf = ps.lib.io.open('./data/DISTRITOS.dbf')
iddist = dbf.by_col('IDDIST')
shp_fips = pd.DataFrame(dbf.by_col('IDDIST'), index=iddist)
shp_fips

             0
100902  100902
100904  100904
250305  250305
250302  250302
250304  250304
...        ...
100608  100608
100609  100609
100610  100610
211105  211105
150806  150806

[1873 rows x 1 columns]

In [105]:
print(w.n)
print(data.shape)

1873
(1874, 16)

### Save the dataframe of input data

In [99]:
if True:
    fn = './data/inputdata_peru.hdf'
    data.to_hdf(fn, 'data')
    print('%s is saved.' % fn)
    fn = './data/inputdata_peru_table.hdf'
    data_name.to_hdf(fn, 'name')
    print('%s is saved.' % fn)

./data/inputdata_peru.hdf is saved.
./data/inputdata_peru_table.hdf is saved.

,PAGE5,PAGE65,PFEMALE,PDISABL,PMEDINS,PNOSWALL,PNOWATER,PNOELEC,PNOSEWAGE,PLITERACY,PNOPRIEDU,PNOCOLLEGE,PRENT,ANUMBFAMILY,PPHONE,PAUTOMOBILE
IDDIST,,,,,,,,,,,,,,,,
10101,0.080794,0.081132,0.526650,0.099573,0.818497,0.049218,0.096125,0.075867,0.146295,0.089122,0.090089,0.848434,0.278042,3.652009,0.926905,0.106472
10102,0.083969,0.179389,0.488550,0.251908,0.954198,0.720000,0.010000,0.150000,0.220000,0.184000,0.156000,0.960000,0.190000,2.466667,0.625000,0.000000
10103,0.097711,0.083627,0.475352,0.090669,0.817782,0.585586,0.330330,0.276276,0.666667,0.178236,0.169794,0.981238,0.201201,3.000000,0.695775,0.036620
10104,0.068536,0.115265,0.506231,0.182243,0.889408,0.278302,0.122642,0.122642,0.169811,0.099673,0.099673,0.968954,0.132075,2.918182,0.740909,0.022727
10105,0.083761,0.140171,0.482051,0.073504,0.947009,0.446078,0.200980,0.343137,0.583333,0.186715,0.179533,0.987433,0.102941,2.839806,0.567961,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250302,0.112199,0.029371,0.484825,0.076170,0.747014,0.830189,0.373344,0.324368,0.803292,0.178152,0.167260,0.974235,0.149338,3.724031,0.698010,0.019899
250303,0.121860,0.034836,0.462704,0.089614,0.645947,0.915217,0.696739,0.235326,0.915761,0.146763,0.142578,0.985631,0.137500,3.998942,0.647558,0.030255
250304,0.122860,0.041348,0.473663,0.079800,0.739004,0.811371,0.276833,0.193411,0.731668,0.143221,0.136145,0.979055,0.180128,3.811077,0.827532,0.044156
250305,0.108818,0.040880,0.472455,0.094218,0.607553,0.860911,0.177458,0.186251,0.614708,0.164972,0.159992,0.974684,0.175060,3.749616,0.796911,0.042471
250401,0.129371,0.035664,0.483566,0.061189,0.914336,0.979502,0.961933,0.584187,0.906296,0.260886,0.229354,0.943318,0.174231,3.972622,0.338663,0.005814

In [ ]:
# fhv.censusToRaster('./census/page5.tif', meta, did, page5)
# fhv.censusToRaster('./census/page5.tif', meta, did, page65)

In [ ]:
# Load a raster of district IDs
with rasterio.open(os.path.join('data', 'distid_30s.tif')) as src:
    did = src.read().squeeze()
    meta = src.meta.copy()
did.shape
meta